Version-Release number of selected component:
anaconda-22.20.13-1

The following was filed automatically by anaconda:
anaconda 22.20.13-1 exception report
Traceback (most recent call first):
  File "/usr/lib64/python2.7/site-packages/gi/overrides/BlockDev.py", line 384, in wrapped
    raise transform[1](msg)
  File "/usr/lib/python2.7/site-packages/blivet/devices/lvm.py", line 628, in _setup
    blockdev.lvm.lvactivate(self.vg.name, self._name)
  File "/usr/lib/python2.7/site-packages/blivet/devices/storage.py", line 430, in setup
    self._setup(orig=orig)
  File "/usr/lib/python2.7/site-packages/blivet/deviceaction.py", line 661, in execute
    self.device.setup(orig=True)
  File "/usr/lib/python2.7/site-packages/blivet/devicetree.py", line 362, in processActions
    action.execute(callbacks)
  File "/usr/lib/python2.7/site-packages/blivet/blivet.py", line 162, in doIt
    self.devicetree.processActions(callbacks)
  File "/usr/lib/python2.7/site-packages/blivet/osinstall.py", line 1057, in turnOnFilesystems
    storage.doIt(callbacks)
  File "/usr/lib64/python2.7/site-packages/pyanaconda/install.py", line 196, in doInstall
    turnOnFilesystems(storage, mountOnly=flags.flags.dirInstall, callbacks=callbacks_reg)
  File "/usr/lib64/python2.7/threading.py", line 766, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib64/python2.7/site-packages/pyanaconda/threads.py", line 244, in run
    threading.Thread.run(self, *args, **kwargs)
LVMError: Process reported exit code 1280:   Volume group "vg0" not found
  Cannot process volume group vg0


Additional info:
addons:         com_redhat_kdump
cmdline:        /usr/bin/python2  /sbin/anaconda
cmdline_file:   BOOT_IMAGE=Fedora-22-x86_64/vmlinuz initrd=Fedora-22-x86_64/initrd.img repo=http://dist.control.lth.se//public/Fedora-22/x86_64/Fedora.release keymap=sv-latin1  BOOTIF=01-70-71-bc-f2-68-ed
dnf.rpm.log:    Jun 23 10:28:31 INFO --- logging initialized ---
executable:     /sbin/anaconda
hashmarkername: anaconda
kernel:         4.0.4-301.fc22.x86_64
product:        Fedora
release:        Cannot get release name.
type:           anaconda
version:        22
Created attachment 1042219
File: anaconda-tb
Created attachment 1042220
File: anaconda.log
Created attachment 1042221
File: dnf.log
Created attachment 1042222
File: environ
Created attachment 1042223
File: lsblk_output
Created attachment 1042224
File: nmcli_dev_list
Created attachment 1042225
File: os_info
Created attachment 1042226
File: program.log
Created attachment 1042227
File: storage.log
Created attachment 1042228
File: syslog
Created attachment 1042229
File: ifcfg.log
Created attachment 1042230
File: packaging.log
*** This bug has been marked as a duplicate of bug 1226244 ***
